//
// PhotosAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class PhotosAPI {

    /**
     Get curated photos
     
     - parameter page: (query) Page number 
     - parameter perPage: (query) Number of photos per page 
     - returns: CuratedPhotosResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getCuratedPhotos(page: Int, perPage: Int) async throws -> CuratedPhotosResponse {
        return try await getCuratedPhotosWithRequestBuilder(page: page, perPage: perPage).execute().body
    }

    /**
     Get curated photos
     - GET /curated
     - Retrieve a list of curated photos from Pexels API
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: ApiKey
     - parameter page: (query) Page number 
     - parameter perPage: (query) Number of photos per page 
     - returns: RequestBuilder<CuratedPhotosResponse> 
     */
    open class func getCuratedPhotosWithRequestBuilder(page: Int, perPage: Int) -> RequestBuilder<CuratedPhotosResponse> {
        let localVariablePath = "/curated"
        let localVariableURLString = LowKeyClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page.encodeToJSON(), isExplode: true),
            "per_page": (wrappedValue: perPage.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CuratedPhotosResponse>.Type = LowKeyClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
