//
// CuratedPhotosResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Curated photos response */
public struct CuratedPhotosResponse: Codable, JSONEncodable {

    public var page: Int?
    public var perPage: Int?
    public var totalResults: Int?
    public var nextPage: String?
    public var photos: [Photo]?

    public init(page: Int? = nil, perPage: Int? = nil, totalResults: Int? = nil, nextPage: String? = nil, photos: [Photo]? = nil) {
        self.page = page
        self.perPage = perPage
        self.totalResults = totalResults
        self.nextPage = nextPage
        self.photos = photos
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case page
        case perPage = "per_page"
        case totalResults = "total_results"
        case nextPage = "next_page"
        case photos
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(page, forKey: .page)
        try container.encodeIfPresent(perPage, forKey: .perPage)
        try container.encodeIfPresent(totalResults, forKey: .totalResults)
        try container.encodeIfPresent(nextPage, forKey: .nextPage)
        try container.encodeIfPresent(photos, forKey: .photos)
    }
}

