//
// Photo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Photo object */
public struct Photo: Codable, JSONEncodable {

    public var photographer: String?
    public var src: PhotoSource?

    public init(photographer: String? = nil, src: PhotoSource? = nil) {
        self.photographer = photographer
        self.src = src
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case photographer
        case src
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(photographer, forKey: .photographer)
        try container.encodeIfPresent(src, forKey: .src)
    }
}

